"""empty message

Revision ID: 7c2c83e43ec8
Revises: 391031fe59d9
Create Date: 2024-01-12 16:28:57.164648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2c83e43ec8'
down_revision = '391031fe59d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
